/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minventario.vistas;

import com.minventario.modelos.tablas.TablaProbabilidad;
import com.minventario.modelos.variables.InventarioBase;
import java.util.ArrayList;

/**
 *
 * @author AntonioPC
 */
public class VistaVariablesEntrada extends javax.swing.JFrame {
    
    private InventarioBase inventario;
    private ArrayList<TablaProbabilidad> demanda = new ArrayList<>();
    private ArrayList<TablaProbabilidad> entrega= new ArrayList<>();
    private ArrayList<TablaProbabilidad> espera= new ArrayList<>();
    
    public VistaVariablesEntrada() {
        initComponents();
    }

    /**
     * Creates new form VistaFormularios
     */
    public VistaVariablesEntrada(InventarioBase inventario, ArrayList<TablaProbabilidad> demanda, 
            ArrayList<TablaProbabilidad> entrega, ArrayList<TablaProbabilidad> espera) {
        initComponents();
        this.inventario = inventario;
        this.demanda = demanda;
        this.entrega = entrega;
        this.espera = espera;
    }
    
    
    public void llenarCampos(){
        jTextFieldInventarioInicial.setText("" + inventario.getInventarioInicial());
        switch(inventario.getUnidadDeTiempo()){
            case 1:
                jRadioButtonDia.setSelected(true);
                break;
            case 2:
                jRadioButtonSemana.setSelected(true);
                break;
            case 3:
                jRadioButtonMes.setSelected(true);
                break;
            case 4:
                jRadioButtonTrimestre.setSelected(true);
                break;
            case 5:
                jRadioButtonSemestre.setSelected(true);
                break;
            case 6:
                jRadioButtonAnual.setSelected(true);
                break;                
        }
        jTextFieldTiempoSimulacion.setText("" + inventario.getTiempoSimulacion());
        jTextFieldCostoInventario.setText("" + inventario.getCostoInventario());
        jTextFieldCostoOrdenar.setText("" + inventario.getCostoOrdernar());
        jTextFieldCostoCompra.setText("" + inventario.getCostoCompra());
        jTextFieldCostoConEspera.setText("" + inventario.getCostoFaltanteConEspera());
        jTextFieldCostoSinEspera.setText("" + inventario.getCostoFaltanteSinEspera());
        jTextFieldCantidadDemanda.setText("" + inventario.getCantidadDemanda());
        jTextFieldCantidadEntrega.setText("" + inventario.getCantidadEntrega());
        jTextFieldCantidadEspera.setText("" + inventario.getCantidadEspera());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesUnidad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldInventarioInicial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCostoOrdenar = new javax.swing.JTextField();
        jTextFieldTiempoSimulacion = new javax.swing.JTextField();
        jTextFieldCostoInventario = new javax.swing.JTextField();
        jTextFieldCostoSinEspera = new javax.swing.JTextField();
        jTextFieldCostoCompra = new javax.swing.JTextField();
        jTextFieldCostoConEspera = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldCantidadDemanda = new javax.swing.JTextField();
        jTextFieldCantidadEspera = new javax.swing.JTextField();
        jTextFieldCantidadEntrega = new javax.swing.JTextField();
        jButtonSiguiente = new javax.swing.JButton();
        jRadioButtonDia = new javax.swing.JRadioButton();
        jRadioButtonSemana = new javax.swing.JRadioButton();
        jRadioButtonMes = new javax.swing.JRadioButton();
        jRadioButtonTrimestre = new javax.swing.JRadioButton();
        jRadioButtonSemestre = new javax.swing.JRadioButton();
        jRadioButtonAnual = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 42, 54));

        jPanel1.setBackground(new java.awt.Color(42, 42, 54));
        jPanel1.setForeground(new java.awt.Color(118, 132, 158));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 558));

        jTextFieldInventarioInicial.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldInventarioInicial.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldInventarioInicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jLabel1.setForeground(new java.awt.Color(118, 132, 158));
        jLabel1.setText("Inventario Inicial");

        jLabel2.setForeground(new java.awt.Color(118, 132, 158));
        jLabel2.setText("Unidad de Tiempo");

        jLabel3.setForeground(new java.awt.Color(118, 132, 158));
        jLabel3.setText("Tiempo de Simulación");

        jLabel4.setForeground(new java.awt.Color(118, 132, 158));
        jLabel4.setText("Costo Inventario");

        jLabel5.setForeground(new java.awt.Color(118, 132, 158));
        jLabel5.setText("Costo Ordenar");

        jLabel6.setForeground(new java.awt.Color(118, 132, 158));
        jLabel6.setText("Costo Compra");

        jLabel7.setForeground(new java.awt.Color(118, 132, 158));
        jLabel7.setText("Costo Faltante C/Espera");

        jLabel8.setForeground(new java.awt.Color(118, 132, 158));
        jLabel8.setText("Costo Faltante S/Espera");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(118, 132, 158));
        jLabel9.setText("MInventario");

        jTextFieldCostoOrdenar.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoOrdenar.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoOrdenar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTextFieldTiempoSimulacion.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldTiempoSimulacion.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldTiempoSimulacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTextFieldCostoInventario.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoInventario.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTextFieldCostoSinEspera.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoSinEspera.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoSinEspera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTextFieldCostoCompra.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoCompra.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTextFieldCostoConEspera.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoConEspera.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoConEspera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jLabel13.setForeground(new java.awt.Color(118, 132, 158));
        jLabel13.setText("$/unidad/año");

        jLabel14.setForeground(new java.awt.Color(118, 132, 158));
        jLabel14.setText("unidades");

        jLabel15.setForeground(new java.awt.Color(118, 132, 158));
        jLabel15.setText("$/orden");

        jLabel16.setForeground(new java.awt.Color(118, 132, 158));
        jLabel16.setText("$/unidad");

        jLabel17.setForeground(new java.awt.Color(118, 132, 158));
        jLabel17.setText("$/unidad");

        jLabel18.setForeground(new java.awt.Color(118, 132, 158));
        jLabel18.setText("$/unidad");

        jLabel10.setForeground(new java.awt.Color(118, 132, 158));
        jLabel10.setText("Demanda Diaria ");

        jLabel11.setForeground(new java.awt.Color(118, 132, 158));
        jLabel11.setText("Tiempo de Entrega");

        jLabel12.setForeground(new java.awt.Color(118, 132, 158));
        jLabel12.setText("Tiempo de Espera");

        jLabel19.setForeground(new java.awt.Color(118, 132, 158));
        jLabel19.setText("Cantidades");

        jTextFieldCantidadDemanda.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCantidadDemanda.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCantidadDemanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTextFieldCantidadEspera.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCantidadEspera.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCantidadEspera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTextFieldCantidadEntrega.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCantidadEntrega.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCantidadEntrega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jButtonSiguiente.setBackground(new java.awt.Color(97, 98, 130));
        jButtonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jRadioButtonDia.setBackground(new java.awt.Color(42, 42, 54));
        botonesUnidad.add(jRadioButtonDia);
        jRadioButtonDia.setForeground(new java.awt.Color(118, 132, 158));
        jRadioButtonDia.setText("Dia");

        jRadioButtonSemana.setBackground(new java.awt.Color(42, 42, 54));
        botonesUnidad.add(jRadioButtonSemana);
        jRadioButtonSemana.setForeground(new java.awt.Color(118, 132, 158));
        jRadioButtonSemana.setText("Semana");

        jRadioButtonMes.setBackground(new java.awt.Color(42, 42, 54));
        botonesUnidad.add(jRadioButtonMes);
        jRadioButtonMes.setForeground(new java.awt.Color(118, 132, 158));
        jRadioButtonMes.setText("Mes");
        jRadioButtonMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMesActionPerformed(evt);
            }
        });

        jRadioButtonTrimestre.setBackground(new java.awt.Color(42, 42, 54));
        botonesUnidad.add(jRadioButtonTrimestre);
        jRadioButtonTrimestre.setForeground(new java.awt.Color(118, 132, 158));
        jRadioButtonTrimestre.setText("Trimestre");
        jRadioButtonTrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTrimestreActionPerformed(evt);
            }
        });

        jRadioButtonSemestre.setBackground(new java.awt.Color(42, 42, 54));
        botonesUnidad.add(jRadioButtonSemestre);
        jRadioButtonSemestre.setForeground(new java.awt.Color(118, 132, 158));
        jRadioButtonSemestre.setText("Semestre");
        jRadioButtonSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSemestreActionPerformed(evt);
            }
        });

        jRadioButtonAnual.setBackground(new java.awt.Color(42, 42, 54));
        botonesUnidad.add(jRadioButtonAnual);
        jRadioButtonAnual.setForeground(new java.awt.Color(118, 132, 158));
        jRadioButtonAnual.setText("Anual");
        jRadioButtonAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAnualActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(118, 132, 158));
        jLabel20.setText("Y luego, ingrese los valores en numeros enteros en cada celda.");

        jLabel21.setForeground(new java.awt.Color(118, 132, 158));
        jLabel21.setText("Seleccione la Unidad de Tiempo a utilizar en el modelo de inventario probabilistico.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCantidadEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCantidadDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCantidadEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCostoConEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCostoSinEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCostoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCostoOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCostoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldInventarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSemana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonTrimestre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSemestre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAnual))
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTiempoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonDia)
                    .addComponent(jRadioButtonSemana)
                    .addComponent(jRadioButtonMes)
                    .addComponent(jRadioButtonTrimestre)
                    .addComponent(jRadioButtonSemestre)
                    .addComponent(jRadioButtonAnual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldInventarioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTiempoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCostoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCostoOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCostoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCostoConEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCostoSinEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCantidadDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCantidadEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldCantidadEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        
        int unidadTiempoSeleccionada = 1;
        
        if (jRadioButtonDia.isSelected()){
            unidadTiempoSeleccionada = 1;
        }
        if (jRadioButtonSemana.isSelected()){
            unidadTiempoSeleccionada = 2;
        }
        if (jRadioButtonMes.isSelected()){
            unidadTiempoSeleccionada = 3;
        }
        if (jRadioButtonTrimestre.isSelected()){
            unidadTiempoSeleccionada = 4;
        }
        if (jRadioButtonSemestre.isSelected()){
            unidadTiempoSeleccionada = 5;
        }
        
        if (jRadioButtonAnual.isSelected()){
            unidadTiempoSeleccionada = 6;
        }
        
        inventario = new InventarioBase(
                Integer.parseInt(jTextFieldInventarioInicial.getText()),
                unidadTiempoSeleccionada,
                Integer.parseInt(jTextFieldTiempoSimulacion.getText()),
                Integer.parseInt(jTextFieldCostoInventario.getText()),
                Integer.parseInt(jTextFieldCostoOrdenar.getText()),
                Integer.parseInt(jTextFieldCostoCompra.getText()),
                Integer.parseInt(jTextFieldCostoConEspera.getText()),
                Integer.parseInt(jTextFieldCostoSinEspera.getText())
        );
        
        inventario.calcularFactorTiempo();
        inventario.calculaCostoInventarioUnitario();
        
        this.setVisible(false);
        VistaTablasEntrada tablas = new VistaTablasEntrada(
                inventario,
                demanda,
                entrega,
                espera,
                Integer.parseInt(jTextFieldCantidadDemanda.getText()),
                Integer.parseInt(jTextFieldCantidadEntrega.getText()),
                Integer.parseInt(jTextFieldCantidadEspera.getText())
        );
        tablas.generarFilas();
        if (demanda != null && entrega != null && espera != null
            && !demanda.isEmpty()&& !entrega.isEmpty() && !espera.isEmpty()){
            tablas.llenarTablas();
        }
        tablas.setVisible(true);
        tablas.setLocationRelativeTo(null);
        tablas.setSize(850, 625);
        tablas.setTitle("MInventario - Tablas de datos - Analisis");
        tablas.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jRadioButtonMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMesActionPerformed

    private void jRadioButtonTrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTrimestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTrimestreActionPerformed

    private void jRadioButtonSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSemestreActionPerformed

    private void jRadioButtonAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAnualActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesUnidad;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAnual;
    private javax.swing.JRadioButton jRadioButtonDia;
    private javax.swing.JRadioButton jRadioButtonMes;
    private javax.swing.JRadioButton jRadioButtonSemana;
    private javax.swing.JRadioButton jRadioButtonSemestre;
    private javax.swing.JRadioButton jRadioButtonTrimestre;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCantidadDemanda;
    private javax.swing.JTextField jTextFieldCantidadEntrega;
    private javax.swing.JTextField jTextFieldCantidadEspera;
    private javax.swing.JTextField jTextFieldCostoCompra;
    private javax.swing.JTextField jTextFieldCostoConEspera;
    private javax.swing.JTextField jTextFieldCostoInventario;
    private javax.swing.JTextField jTextFieldCostoOrdenar;
    private javax.swing.JTextField jTextFieldCostoSinEspera;
    private javax.swing.JTextField jTextFieldInventarioInicial;
    private javax.swing.JTextField jTextFieldTiempoSimulacion;
    // End of variables declaration//GEN-END:variables
}
