/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minventario.vistas;

import com.minventario.modelos.Main;
import com.minventario.modelos.tablas.TablaProbabilidad;
import com.minventario.modelos.variables.InventarioBase;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cisco
 */
public class VistaTablasEntrada extends javax.swing.JFrame {

    private InventarioBase inventario;
    private int cantidadDemanda;
    private int cantidadEntrega;
    private int cantidadEspera;
    private ArrayList<TablaProbabilidad> demanda = new ArrayList<>();
    private ArrayList<TablaProbabilidad> entrega = new ArrayList<>();
    private ArrayList<TablaProbabilidad> espera = new ArrayList<>();
    private ArrayList<Integer> demandaNumerosAleatorios = new ArrayList<>();
    private ArrayList<Integer> entregaNumerosAleatorios = new ArrayList<>();
    private ArrayList<Integer> esperaNumerosAleatorios = new ArrayList<>();
    private int conteoGuardar = 0;

    public ArrayList<Integer> getDemandaNumerosAleatorios() {
        return demandaNumerosAleatorios;
    }

    public ArrayList<Integer> getEntregaNumerosAleatorios() {
        return entregaNumerosAleatorios;
    }

    public ArrayList<Integer> getEsperaNumerosAleatorios() {
        return esperaNumerosAleatorios;
    }

    /**
     * Creates new form VistaTablas
     */
    public VistaTablasEntrada(InventarioBase inventario, ArrayList<TablaProbabilidad> demanda, 
            ArrayList<TablaProbabilidad> entrega, ArrayList<TablaProbabilidad> espera, 
            int cantidadDemanda, int cantidadEntrega, int cantidadEspera) {
        initComponents();
        String PayneGrey = "#616282";
        String LowGrey = "#CCCCCC";
        jTableDemanda.getTableHeader().setBackground(Color.decode(PayneGrey));
        jTableDemanda.getTableHeader().setForeground(Color.decode(LowGrey));
        jTableEntrega.getTableHeader().setBackground(Color.decode(PayneGrey));
        jTableEntrega.getTableHeader().setForeground(Color.decode(LowGrey));
        jTableEspera.getTableHeader().setBackground(Color.decode(PayneGrey));
        jTableEspera.getTableHeader().setForeground(Color.decode(LowGrey));
        this.inventario = inventario;
        this.demanda = demanda;
        this.entrega = entrega;
        this.espera = espera;
        this.cantidadDemanda = cantidadDemanda;
        this.cantidadEntrega = cantidadEntrega;
        this.cantidadEspera = cantidadEspera;
    }
       
    public void generarFilas() {
        DefaultTableModel modelDemanda = (DefaultTableModel) jTableDemanda.getModel();
        DefaultTableModel modelEntrega = (DefaultTableModel) jTableEntrega.getModel();
        DefaultTableModel modelEspera = (DefaultTableModel) jTableEspera.getModel();
       
        for (int i=0;i<cantidadDemanda;i++) {
            modelDemanda.addRow(new Object[]{0, 0.0, 0.0});
        }
        for (int i=0;i<cantidadEntrega;i++) {
            modelEntrega.addRow(new Object[]{0, 0.0, 0.0});
        }
        for (int i=0;i<cantidadEspera;i++) {
            modelEspera.addRow(new Object[]{0, 0.0, 0.0});
        }
    }
    
    public void llenarTablas(){
        for (int i=0;i<cantidadDemanda;i++) {
            jTableDemanda.setValueAt(demanda.get(i).getValor(), i, 0);
            jTableDemanda.setValueAt(demanda.get(i).getProbabilidad(), i, 1);
        }
        for (int i=0;i<cantidadEntrega;i++) {
            jTableEntrega.setValueAt(entrega.get(i).getValor(), i, 0);
            jTableEntrega.setValueAt(entrega.get(i).getProbabilidad(), i, 1);
        }
        for (int i=0;i<cantidadEspera;i++) {
            jTableEspera.setValueAt(espera.get(i).getValor(), i, 0);
            jTableEspera.setValueAt(espera.get(i).getProbabilidad(), i, 1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDemanda = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEspera = new javax.swing.JTable();
        jButtonValoresAleatorios = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCantidadEntregasAleatorias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCantidadDemandasAleatorias = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCantidadEsperasAleatorias = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonResultados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntrega = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldVariableQ = new javax.swing.JTextField();
        jTextFieldVariableR = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButtonTablaAnalisis = new javax.swing.JButton();
        jButtonGuardarDatos = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 42, 54));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(42, 42, 54));
        jPanel1.setPreferredSize(new java.awt.Dimension(719, 600));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(118, 132, 158));
        jLabel9.setText("MInventario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 132, 158));
        jLabel1.setText("Demanda");

        jScrollPane2.setBackground(new java.awt.Color(95, 80, 107));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTableDemanda.setBackground(new java.awt.Color(95, 80, 107));
        jTableDemanda.setForeground(new java.awt.Color(204, 204, 204));
        jTableDemanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Probabilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableDemanda.setFillsViewportHeight(true);
        jTableDemanda.setSelectionBackground(new java.awt.Color(117, 72, 94));
        jTableDemanda.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jTableDemanda);

        jScrollPane3.setBackground(new java.awt.Color(95, 80, 107));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTableEspera.setBackground(new java.awt.Color(95, 80, 107));
        jTableEspera.setForeground(new java.awt.Color(204, 204, 204));
        jTableEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Probabilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEspera.setFillsViewportHeight(true);
        jTableEspera.setSelectionBackground(new java.awt.Color(117, 72, 94));
        jTableEspera.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(jTableEspera);

        jButtonValoresAleatorios.setBackground(new java.awt.Color(97, 98, 130));
        jButtonValoresAleatorios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonValoresAleatorios.setText("Llenar datos");
        jButtonValoresAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValoresAleatoriosActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(118, 132, 158));
        jLabel5.setText("Ingresar los numeros aleatorios manualmente");

        jTextFieldCantidadEntregasAleatorias.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCantidadEntregasAleatorias.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCantidadEntregasAleatorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jLabel6.setForeground(new java.awt.Color(118, 132, 158));
        jLabel6.setText("Demanda");

        jTextFieldCantidadDemandasAleatorias.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCantidadDemandasAleatorias.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCantidadDemandasAleatorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jLabel7.setForeground(new java.awt.Color(118, 132, 158));
        jLabel7.setText("En cada cuadro de texto colocar el numero de valores aleatorios que desea usar");

        jLabel8.setForeground(new java.awt.Color(118, 132, 158));
        jLabel8.setText("Tiempo de Entrega");

        jTextFieldCantidadEsperasAleatorias.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCantidadEsperasAleatorias.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCantidadEsperasAleatorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jLabel11.setForeground(new java.awt.Color(118, 132, 158));
        jLabel11.setText("Y presione el botón de siguiente para llenar las tablas respectivas de numeros aleatorios");

        jLabel10.setForeground(new java.awt.Color(118, 132, 158));
        jLabel10.setText("Tiempo de Espera");

        jLabel12.setForeground(new java.awt.Color(118, 132, 158));
        jLabel12.setText("Para obtener los resultados llene las tablas con los respectivos datos y presione el botón de \"Calcular tabla de resultados\"");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 132, 158));
        jLabel4.setText("OPCIONAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 132, 158));
        jLabel2.setText("Tiempo de Entrega");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 132, 158));
        jLabel3.setText("Tiempo de Espera");

        jButtonResultados.setBackground(new java.awt.Color(97, 98, 130));
        jButtonResultados.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResultados.setText("Calcular tabla de resultados");
        jButtonResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadosActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(95, 80, 107));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTableEntrega.setBackground(new java.awt.Color(95, 80, 107));
        jTableEntrega.setForeground(new java.awt.Color(204, 204, 204));
        jTableEntrega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Probabilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEntrega.setFillsViewportHeight(true);
        jTableEntrega.setSelectionBackground(new java.awt.Color(117, 72, 94));
        jTableEntrega.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTableEntrega);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextFieldVariableQ.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldVariableQ.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldVariableQ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTextFieldVariableR.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldVariableR.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldVariableR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(118, 132, 158));
        jLabel13.setText("ANALISIS");

        jLabel14.setForeground(new java.awt.Color(118, 132, 158));
        jLabel14.setText("Dado un valor del inventario por pedido");

        jLabel15.setForeground(new java.awt.Color(118, 132, 158));
        jLabel15.setText("Y el punto de reorden");

        jLabel16.setForeground(new java.awt.Color(118, 132, 158));
        jLabel16.setText("Se pueden probar los datos");

        jLabel17.setForeground(new java.awt.Color(118, 132, 158));
        jLabel17.setText("Parar generar su respectiva tabla de eventos");

        jLabel18.setForeground(new java.awt.Color(118, 132, 158));
        jLabel18.setText("Inventario por pedido");

        jLabel19.setForeground(new java.awt.Color(118, 132, 158));
        jLabel19.setText("Punto de Reorden");

        jButtonTablaAnalisis.setBackground(new java.awt.Color(97, 98, 130));
        jButtonTablaAnalisis.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTablaAnalisis.setText("Mostrar tabla");
        jButtonTablaAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTablaAnalisisActionPerformed(evt);
            }
        });

        jButtonGuardarDatos.setBackground(new java.awt.Color(95, 80, 107));
        jButtonGuardarDatos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardarDatos.setText("Guardar datos de las tablas");
        jButtonGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarDatosActionPerformed(evt);
            }
        });

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(118, 132, 158));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCantidadDemandasAleatorias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCantidadEntregasAleatorias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCantidadEsperasAleatorias, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonValoresAleatorios)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVariableQ, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldVariableR, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTablaAnalisis))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonResultados)
                                                    .addComponent(jButtonGuardarDatos)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jLabelMensaje))))))
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButtonResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMensaje))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldCantidadDemandasAleatorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jButtonValoresAleatorios)
                                    .addComponent(jTextFieldCantidadEntregasAleatorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldCantidadEsperasAleatorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldVariableQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldVariableR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonTablaAnalisis)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadosActionPerformed

        Main.comprobarTeoriaProbabilidadTotal(demanda);
        Main.comprobarTeoriaProbabilidadTotal(entrega);
        Main.comprobarTeoriaProbabilidadTotal(espera);

        inventario.calcularQR(
            demanda.get(0).getValor(),
            demanda.get(demanda.size() - 1).getValor(),
            entrega.get(0).getValor(),
            entrega.get(entrega.size() - 1).getValor());

        this.setVisible(false);
        VistaResultados resultados = new VistaResultados(inventario, demanda, entrega, espera, 
                demandaNumerosAleatorios, entregaNumerosAleatorios, esperaNumerosAleatorios);
        resultados.rellenarVista();
        resultados.setLocationRelativeTo(null);
        resultados.setTitle("MInventario - Resultados");
        resultados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonResultadosActionPerformed

    private void jButtonValoresAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValoresAleatoriosActionPerformed
        
        int cantidadDemandasAleatorias = Integer.parseInt(jTextFieldCantidadDemandasAleatorias.getText());
        int cantidadEntregasAleatorias = Integer.parseInt(jTextFieldCantidadEntregasAleatorias.getText());
        int cantidadEsperasAleatorias = Integer.parseInt(jTextFieldCantidadEsperasAleatorias.getText());
        
        VistaTablasAleatorias aleatorias = new VistaTablasAleatorias(this, cantidadDemandasAleatorias,
                                                                     cantidadEntregasAleatorias,
                                                                     cantidadEsperasAleatorias);
        aleatorias.generarFilas();
        aleatorias.setVisible(true);
        aleatorias.setFocusable(true);
        aleatorias.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonValoresAleatoriosActionPerformed

    private void jButtonTablaAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTablaAnalisisActionPerformed
        int variableQ = Integer.parseInt(jTextFieldVariableQ.getText());
        int variableR = Integer.parseInt(jTextFieldVariableR.getText());
        VistaAnalisis analisis = new VistaAnalisis(variableQ, variableR, inventario, demanda, entrega, espera, 
                demandaNumerosAleatorios, entregaNumerosAleatorios, esperaNumerosAleatorios);
        analisis.setLocationRelativeTo(null);
        analisis.setTitle("Tabla de analisis para Q=" + variableQ + " y R=" + variableR);
        analisis.generarFilas();
        analisis.llenarTabla();
        analisis.setVisible(true);
        analisis.setFocusable(true);
    }//GEN-LAST:event_jButtonTablaAnalisisActionPerformed

    private void jButtonGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarDatosActionPerformed
        for (int i = 0; i < jTableDemanda.getRowCount(); i++) {
            demanda.add(new TablaProbabilidad(
                Integer.parseInt(jTableDemanda.getValueAt(i, 0).toString()),
                Double.parseDouble(jTableDemanda.getValueAt(i, 1).toString())
            )
        );
        }
        for (int i = 0; i < jTableEntrega.getRowCount(); i++) {
            entrega.add(new TablaProbabilidad(
                Integer.parseInt(jTableEntrega.getValueAt(i, 0).toString()),
                Double.parseDouble(jTableEntrega.getValueAt(i, 1).toString())
            )
        );
        }
        for (int i = 0; i < jTableEspera.getRowCount(); i++) {
            espera.add(new TablaProbabilidad(
                Integer.parseInt(jTableEspera.getValueAt(i, 0).toString()),
                Double.parseDouble(jTableEspera.getValueAt(i, 1).toString())
            )
        );
        }
        conteoGuardar++;
        jLabelMensaje.setText("¡Datos guardados! [" + conteoGuardar + "]");

    }//GEN-LAST:event_jButtonGuardarDatosActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarDatos;
    private javax.swing.JButton jButtonResultados;
    private javax.swing.JButton jButtonTablaAnalisis;
    private javax.swing.JButton jButtonValoresAleatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableDemanda;
    private javax.swing.JTable jTableEntrega;
    private javax.swing.JTable jTableEspera;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCantidadDemandasAleatorias;
    private javax.swing.JTextField jTextFieldCantidadEntregasAleatorias;
    private javax.swing.JTextField jTextFieldCantidadEsperasAleatorias;
    private javax.swing.JTextField jTextFieldVariableQ;
    private javax.swing.JTextField jTextFieldVariableR;
    // End of variables declaration//GEN-END:variables
}
