/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minventario.vistas;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AntonioPC
 */
public class VistaTablasAleatorias extends javax.swing.JFrame {

    int cantidadDemandasAleatorias;
    int cantidadEntregasAleatorias;
    int cantidadEsperasAleatorias;
    VistaTablasEntrada vistaTablasEntrada;
    
    /**
     * Creates new form VistaTablasAleatorias
     */
    public VistaTablasAleatorias(VistaTablasEntrada vistaTablasEntrada, int cantidadDemandasAleatorias, 
                                int cantidadEntregasAleatorias, int cantidadEsperasAleatorias) {
        initComponents();
        this.vistaTablasEntrada = vistaTablasEntrada;
        this.cantidadDemandasAleatorias = cantidadDemandasAleatorias;
        this.cantidadEntregasAleatorias = cantidadEntregasAleatorias;
        this.cantidadEsperasAleatorias = cantidadEsperasAleatorias;
    }
    
    public void generarFilas() {
        DefaultTableModel modelDemanda = (DefaultTableModel) jTableDemanda.getModel();
        DefaultTableModel modelEntrega = (DefaultTableModel) jTableEntrega.getModel();
        DefaultTableModel modelEspera = (DefaultTableModel) jTableEspera.getModel();
       
        for (int i=0;i<cantidadDemandasAleatorias;i++) {
            modelDemanda.addRow(new Object[]{0});
        }
        for (int i=0;i<cantidadEntregasAleatorias;i++) {
            modelEntrega.addRow(new Object[]{0});
        }
        for (int i=0;i<cantidadEsperasAleatorias;i++) {
            modelEspera.addRow(new Object[]{0});
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntrega = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEspera = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDemanda = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 42, 54));

        jScrollPane1.setBackground(new java.awt.Color(95, 80, 107));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTableEntrega.setBackground(new java.awt.Color(95, 80, 107));
        jTableEntrega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor Aleatorio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEntrega.setFillsViewportHeight(true);
        jTableEntrega.setSelectionBackground(new java.awt.Color(117, 72, 94));
        jTableEntrega.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTableEntrega);

        jScrollPane3.setBackground(new java.awt.Color(95, 80, 107));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTableEspera.setBackground(new java.awt.Color(95, 80, 107));
        jTableEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor Aleatorio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEspera.setFillsViewportHeight(true);
        jTableEspera.setSelectionBackground(new java.awt.Color(117, 72, 94));
        jTableEspera.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(jTableEspera);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(118, 132, 158));
        jLabel3.setText("Tiempo de Espera");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(118, 132, 158));
        jLabel2.setText("Tiempo de Entrega");

        jScrollPane2.setBackground(new java.awt.Color(95, 80, 107));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTableDemanda.setBackground(new java.awt.Color(95, 80, 107));
        jTableDemanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor Aleatorio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableDemanda.setFillsViewportHeight(true);
        jTableDemanda.setSelectionBackground(new java.awt.Color(117, 72, 94));
        jTableDemanda.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jTableDemanda);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(118, 132, 158));
        jLabel4.setText("Demanda");

        jButtonGuardar.setBackground(new java.awt.Color(97, 98, 130));
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar valores aleatorios");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(118, 132, 158));
        jLabel9.setText("MInventario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGuardar)
                                .addGap(90, 90, 90))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel9)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jButtonGuardar)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        for (int i=0; i<jTableDemanda.getRowCount(); i++){
            vistaTablasEntrada.getDemandaNumerosAleatorios().add(
                    Integer.parseInt(jTableDemanda.getValueAt(i, 0).toString())
            );
        }
        
        for (int i=0; i<jTableEntrega.getRowCount(); i++){
            vistaTablasEntrada.getEntregaNumerosAleatorios().add(
                    Integer.parseInt(jTableEntrega.getValueAt(i, 0).toString())
            );
        }
                
        for (int i=0; i<jTableEspera.getRowCount(); i++){
            vistaTablasEntrada.getEsperaNumerosAleatorios().add(
                    Integer.parseInt(jTableEspera.getValueAt(i, 0).toString())
            );
        }
        
        this.dispose();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDemanda;
    private javax.swing.JTable jTableEntrega;
    private javax.swing.JTable jTableEspera;
    // End of variables declaration//GEN-END:variables
}
