/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.minventario.vistas;

import com.minventario.modelos.algoritmos.Politica;
import com.minventario.modelos.tablas.TablaProbabilidad;
import com.minventario.modelos.variables.InventarioBase;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author cisco
 */
public class VistaResultados extends javax.swing.JFrame {

    private InventarioBase inventario;
    private ArrayList<TablaProbabilidad> demanda = new ArrayList<>();
    private ArrayList<TablaProbabilidad> entrega= new ArrayList<>();
    private ArrayList<TablaProbabilidad> espera= new ArrayList<>();
    private ArrayList<Integer> demandaNumerosAleatorios;
    private ArrayList<Integer> entregaNumerosAleatorios;
    private ArrayList<Integer> esperaNumerosAleatorios;
    
    /**
     * Creates new form VistaResultados
     */
    public VistaResultados(InventarioBase inventario, ArrayList<TablaProbabilidad> demanda, 
            ArrayList<TablaProbabilidad> entrega, ArrayList<TablaProbabilidad> espera,
            ArrayList<Integer> demandaNumerosAleatorios, ArrayList<Integer> entregaNumerosAleatorios, 
            ArrayList<Integer> esperaNumerosAleatorios) {
        initComponents();
        String PayneGrey = "#616282";
        String LowGrey = "#CCCCCC";
        jTableResultados.getTableHeader().setBackground(Color.decode(PayneGrey));
        jTableResultados.getTableHeader().setForeground(Color.decode(LowGrey));
        this.inventario = inventario;
        this.demanda = demanda;
        this.entrega = entrega;
        this.espera = espera;
        this.demandaNumerosAleatorios = demandaNumerosAleatorios;
        this.entregaNumerosAleatorios = entregaNumerosAleatorios;
        this.esperaNumerosAleatorios = esperaNumerosAleatorios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCostoFaltante = new javax.swing.JTextField();
        jTextFieldQ = new javax.swing.JTextField();
        jTextFieldCostoInventario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCostoOrdenar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCostoTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCostoCompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 42, 54));

        jPanel1.setBackground(new java.awt.Color(42, 42, 54));

        jScrollPane1.setBackground(new java.awt.Color(95, 80, 107));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 153)));

        jTableResultados.setBackground(new java.awt.Color(95, 80, 107));
        jTableResultados.setForeground(new java.awt.Color(204, 204, 204));
        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Q", "R", "Costo Compra", "Costo Faltante", "Costo Ordenar", "Costo Inventario", "Costo Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResultados.setFillsViewportHeight(true);
        jTableResultados.setSelectionBackground(new java.awt.Color(117, 72, 94));
        jTableResultados.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTableResultados);
        if (jTableResultados.getColumnModel().getColumnCount() > 0) {
            jTableResultados.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(118, 132, 158));
        jLabel9.setText("MInventario");

        jLabel1.setForeground(new java.awt.Color(118, 132, 158));
        jLabel1.setText("Cantidades optimas");

        jLabel2.setForeground(new java.awt.Color(118, 132, 158));
        jLabel2.setText("Costo Compra");

        jLabel3.setForeground(new java.awt.Color(118, 132, 158));
        jLabel3.setText("Costo Faltante");

        jTextFieldCostoFaltante.setEditable(false);
        jTextFieldCostoFaltante.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoFaltante.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoFaltante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 0, 36)));

        jTextFieldQ.setEditable(false);
        jTextFieldQ.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldQ.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldQ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 0, 36)));

        jTextFieldCostoInventario.setEditable(false);
        jTextFieldCostoInventario.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoInventario.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 0, 36)));

        jLabel4.setForeground(new java.awt.Color(118, 132, 158));
        jLabel4.setText("Costo Ordenar");

        jLabel5.setForeground(new java.awt.Color(118, 132, 158));
        jLabel5.setText("Costo Inventario");

        jTextFieldCostoOrdenar.setEditable(false);
        jTextFieldCostoOrdenar.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoOrdenar.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoOrdenar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 0, 36)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(118, 132, 158));
        jLabel6.setText("Costo Total:");

        jTextFieldCostoTotal.setEditable(false);
        jTextFieldCostoTotal.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoTotal.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 0, 36)));

        jLabel7.setForeground(new java.awt.Color(118, 132, 158));
        jLabel7.setText("Q");

        jTextFieldCostoCompra.setEditable(false);
        jTextFieldCostoCompra.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldCostoCompra.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCostoCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 0, 36)));

        jLabel8.setForeground(new java.awt.Color(118, 132, 158));
        jLabel8.setText("R");

        jTextFieldR.setEditable(false);
        jTextFieldR.setBackground(new java.awt.Color(117, 72, 94));
        jTextFieldR.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 0, 36)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(264, 264, 264)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCostoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCostoOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCostoFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCostoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel1)
                    .addGap(3, 3, 3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jTextFieldCostoOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCostoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextFieldCostoFaltante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldCostoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void rellenarVista() {
       DecimalFormat df2 = new DecimalFormat("#.##");
       Politica pol = new Politica();
       pol.obtenerValoresOptimos(inventario, demanda, entrega, espera, 
               demandaNumerosAleatorios, entregaNumerosAleatorios, esperaNumerosAleatorios);
       jTextFieldQ.setText("" + pol.getqIdeal());
       jTextFieldR.setText("" + pol.getrIdeal());
       jTextFieldCostoCompra.setText(df2.format(pol.getResultadosOptimos().getCostoCompra()));
       jTextFieldCostoFaltante.setText(df2.format(pol.getResultadosOptimos().getCostoFaltante()));
       jTextFieldCostoInventario.setText(df2.format(pol.getResultadosOptimos().getCostoInventario()));
       jTextFieldCostoOrdenar.setText(df2.format(pol.getResultadosOptimos().getCostoOrdenar()));
       jTextFieldCostoTotal.setText(df2.format(pol.getResultadosOptimos().getCostoTotal()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTableResultados;
    private javax.swing.JTextField jTextFieldCostoCompra;
    private javax.swing.JTextField jTextFieldCostoFaltante;
    private javax.swing.JTextField jTextFieldCostoInventario;
    private javax.swing.JTextField jTextFieldCostoOrdenar;
    private javax.swing.JTextField jTextFieldCostoTotal;
    private javax.swing.JTextField jTextFieldQ;
    private javax.swing.JTextField jTextFieldR;
    // End of variables declaration//GEN-END:variables
}
